config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  get 'homes/index'
  devise_for :users, controllers: { registrations: 'registrations' }

  get 'reservations/index'
  resources :reservations, only: [:index, :destroy]  # 追加

  resources :rooms do
    collection do
      get 'search'
    end
    resources :reservations, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get 'profile'
      put 'profile', to: 'users#update_profile'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms
  has_many :reservations

  has_one_attached :icon

  def icon_url
    if icon.attached?
      icon.variant(resize: "400x300").processed
    else
      default_icon_url
    end
  end

  def default_icon_url
    'default-icon.png'
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true, length: {maximum: 50}

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    if current_user.update(user_params)
      flash[:success] = "プロフィールが更新されました"
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
  end

  def profile
    @user = current_user
  end

  def update_profile
    if current_user.update(user_params)
      flash[:success] = "プロフィールが更新されました"
      redirect_to user_path(current_user)
    else
      render :profile
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :icon)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/profile.html.erb
<div class="container">
  <h2>プロフィール</h2>
  <div class="row">
    <div class="col-md-3">
      <p>プロフィール画像</p>
    </div>
    <div class="col-md-9">
      <% if @user.icon.attached? %>
        <%= image_tag url_for(@user.icon.variant(resize: "200x200")), class: "img-fluid" %>
      <% else %>
        <%= image_tag 'homes/default-icon.png', class: "img-fluid" %>
      <% end %>
    </div>
    <div class="col-md-3">
      <p>名前</p>
    </div>
    <div class="col-md-9">
      <div class="mb-3">
        <%= @user.name %>
      </div>
    </div>
    <div class="col-md-3">
      <p>自己紹介</p>
    </div>
    <div class="col-md-9">
      <div class="mb-3">
        <%= @user.introduction %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <h2>プロフィール編集</h2>
  <%= form_for(@user, url: profile_user_path(@user), method: :put) do |f| %>
    <div class="mb-3">
      <%= f.label :名前 %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :自己紹介 %>
      <%= f.text_area :introduction, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :icon, "プロフィール画像" %>
      <%= f.file_field :icon, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.submit "更新", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h2><%= @user.name %></h2>
  
  <div class="row">
    <div class="col-md-6">
      <h3 class="mb-4">プロフィール</h3>
      <div class="row">
        <div class="col-md-3">
          <p>プロフィール画像</p>
        </div>
        <div class="col-md-9">
          <% if @user.icon.attached? %>
            <%= image_tag url_for(@user.icon.variant(resize: "200x200")), class: "img-fluid" %>
          <% else %>
            <%= image_tag 'default-icon.png', class: "img-fluid" %>
          <% end %>
        </div>
        
        <div class="col-md-3">
          <p>名前</p>
        </div>
        <div class="col-md-9">
          <div class="mb-3">
            <%= @user.name %>
          </div>
        </div>
        
        <div class="col-md-3">
          <p>自己紹介</p>
        </div>
        <div class="col-md-9">
          <div class="mb-3">
            <%= @user.introduction %>
          </div>
        </div>
        
        <div class="col-md-12 text-end">
          <%= link_to "プロフィールを編集", profile_user_path(@user), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    
    <div class="col-md-6">
      <h3 class="mb-4">アカウント情報</h3>
      <div class="row">
        <div class="col-md-3">
          <p>メールアドレス</p>
        </div>
        <div class="col-md-9">
          <div class="mb-3">
            <%= @user.email %>
          </div>
        </div>
        <div class="col-md-3">
          <p>パスワード</p>
        </div>
        <div class="col-md-9">
          <div class="mb-3">
            *********
          </div>
        </div>
        
        <div class="col-md-12 text-end">
          <%= link_to "アカウント情報を編集", edit_user_registration_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  
  <hr>
</div>