config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  get 'homes/index'
  devise_for :users, controllers: { registrations: 'registrations' }

  get 'reservations/index'
  resources :reservations, only: [:index, :destroy]  # 追加

  resources :rooms do
    collection do
      get 'search'
    end
    resources :reservations, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get 'profile'
      put 'profile', to: 'users#update_profile'
    end
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :reserve_start, presence: true
  validates :reserve_end, presence: true

  validate :start_date_not_past
  validate :end_date_after_start_date

  def start_date_not_past
    return if reserve_start.blank?

    if reserve_start < Date.today
      errors.add(:reserve_start, "は過去の日付を選択することはできません")
    end
  end

  def end_date_after_start_date
    if reserve_end.present? && reserve_start.present? && reserve_end <= reserve_start
      errors.add(:reserve_end, "はチェックイン日よりも後の日付を選択してください")
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @reservations = Reservation.where(user_id: current_user.id).all
    @room = Room.where(user_id: current_user.id).all
  end

  def new
    @room = Room.find(params[:room_id])
    @user = current_user
    if @room && @user
      @reservation = Reservation.new
    else
      redirect_to root_path, alert: "エラーが発生しました。"
    end
  end

  def create
    @user = current_user
    @room = Room.find(params[:room_id])
    @reservation = Reservation.new(reservation_params)
  
    if @reservation.reserve_start.present? && @reservation.reserve_end.present?
      @reservation.reserve_days = (@reservation.reserve_end - @reservation.reserve_start).to_i
      @reservation.reserve_total = @reservation.reserve_price * @reservation.reserve_people * @reservation.reserve_days
  
      if @reservation.save
          flash[:notice] = "予約が完了しました。"
          redirect_to reservations_path
      else
          flash.now[:alert] = "予約できませんでした"
          render :new
      end
    else
      flash.now[:alert] = "開始日と終了日を入力してください"
      render :new
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    if @reservation.destroy
      redirect_to reservations_path, notice: "予約を削除しました。"
    else
      flash[:alert] = "問題が発生しました。"
      render "index"
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:room_id, :user_id, :reserve_start, :reserve_end, :reserve_people, :reserve_price, :reserve_days)
  end
end

app/views/reservations/_form.html.erb
<h2>施設の予約</h2>

  <%= form_with model: [@room, @reservations], method: :post , local: true do |f| %>
    <%= f.hidden_field :room_id, value:@room.id %>
    <%= f.hidden_field :user_id, value:current_user.id %>
    <%= f.hidden_field :reserve_price, value:@room.room_price %>

     <table>
        <tr>
          <th><%= f.label :reserve_start, "チェックイン" %></th>
          <td><%= f.date_field :reserve_start %></td>
        </tr>

        <tr>
          <th><%= f.label :reserve_end, "チェックアウト", class: "control-label" %></th>
          <td><%= f.date_field :reserve_end %></td>
        </tr>

        <tr>
          <th><%= f.label :reserve_people, "人数" %></th>
          <td><%= f.number_field :reserve_people, min: 1 %></td>
        </tr>
      </table>

      <div>
        <ul>
          <li><%= f.submit "予約する"%></li>
        </ul>
      </div>
  <% end %>

</div>

app/views/reservations/confirm.html.erb
<div class = "container">
		<h2>予約内容の確認</h2>

		<dt>施設名</dt>
		<dd><%= @reservation.room.room_name %></dd>
		<dt>チェックイン日</dt>
		<dd><%= @reservation.reserve_start %></dd>
		<dt>チェックアウト日</dt>
		<dd><%= @reservation.reserve_end %></dd>
		<dt>人数</dt>
		<dd><%= @reservation.reserve_people %>名</dd>
		<dt>支払い金額</dt>
		<dd>¥<%= @reservation.reserve_total %></dd>
		
    <%= form_with model: [@room, @reservation] do |f| %>
			<%= f.hidden_field :reserve_start %>
			<%= f.hidden_field :reserve_end %>
			<%= f.hidden_field :reserve_people %>
			<%= f.hidden_field :room_id %>
			<%= f.hidden_field :user_id %>
      <div class = "btn">
        <%= f.submit "予約を確定する" %>
		<% end %>
</div>

app/views/reservations/index.html.erb
<div class="container">
  <h2>予約一覧</h2>
  <div class="row">
    <% @reservations.each do |reservation| %>
      <div class="col-md-4 mb-4">
        <div class="card">
          <% if reservation.room.room_image.attached? %>
            <%= image_tag reservation.room.room_image.variant(resize: "400x300"), class: "card-img-top" %>
          <% else %>
            <%= image_tag "default-image-room.png", class: "card-img-top" %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= reservation.room.room_name %></h5>
            <p class="card-text">チェックイン: <%= reservation.reserve_start %></p>
            <p class="card-text">チェックアウト: <%= reservation.reserve_end %></p>
            <p class="card-text">合計料金: <%= reservation.reserve_total %></p>
            <p class="card-text">予約確定日時: <%= reservation.created_at.strftime("%Y年%m月%d日 %H時%M分%S秒") %></p>

            <%= link_to "削除", reservation_path(reservation), method: :delete, data: { confirm: "予約を削除しますか？" }, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reservations/new.html.erb
<%= render "shared/error", obj: @reservation %>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h2 class="mb-4">予約フォーム</h2>
      <h4><%= @room.room_name %></h4>

      <%= form_with model: [@room, @reservation], method: :post, local: true do |f| %>
        <div class="mb-3">
          <%= f.label :reserve_start, "チェックイン日" %>
          <%= f.date_field :reserve_start, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :reserve_end, "チェックアウト日" %>
          <%= f.date_field :reserve_end, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :reserve_people, "人数" %>
          <%= f.number_field :reserve_people, min: 1, class: "form-control" %>
        </div>

        <div>
          <%= f.hidden_field :user_id, value: @user.id %>
          <%= f.hidden_field :room_id, value: @room.id %>
          <%= f.hidden_field :reserve_price, value: @room.room_price %>
          <%= f.hidden_field :room_name, value: @room.room_name %>
        </div>

        <div class="text-end">
          <%= f.submit "予約", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reservations/your_trip.html.erb
<section class="section">
  <div class="container">
    <p class="title">ご予約内容</p>
    <br/>
    <table class="table is-fullwidth" style="text-align: center;">
      <thead>
        <tr>
          <th>申し込み日</th>
          <th>ステータス</th>
          <th>お部屋</th>
          <th>ホスト</th>
          <th></th>
          <th>料金</th>
          <th>アクション</th>
        </tr>
      </thead>
      <tbody>
        <% if @trips.blank? %>
          <tr>
            <td colspan="7" class="has-text-centered"><h1>表示できるご予約はありません。</h1></td>
          </tr>
        <% end %>
        <% @trips.each do |trip| %>
          <tr>
            <td style="padding-top: 30px;">
              <%= I18n.l(trip.created_at, format: :full_date) %>
            </td>
            <!-- ステータス -->
            <td style="padding-top: 30px;">
            </td>
            <td>
              <%= link_to room_path(trip.room), data: { turbolinks: false} do %>                                
                <%= image_tag room_cover(trip.room), class: "image is-64x64" %>
                <%= trip.room.listing_name %>
              <% end %>
            </td>
            <td style="padding-top: 30px;">
              <%= link_to user_path(trip.room.user), class: "tootip" do %>
                <figure class="image is-48x48">
                  <%= image_tag avatar_url(trip.room.user), class: "is-rounded" %>
                </figure>
                  <%= trip.room.user.full_name %>
              <% end %>
            </td>
            <td style="padding-top: 30px;">
              宿泊日：<%= I18n.l(trip.start_date, format: :full_date) %><br/>
              ご出発：<%= I18n.l(trip.end_date, format: :full_date) %>
            </td>
            <td style="padding-top: 30px;"><%= number_to_currency(trip.total) %></td>
            <!-- アクション -->
            <td style="padding-top: 30px;">
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>