config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  get 'homes/index'
  devise_for :users, controllers: { registrations: 'registrations' }

  get 'reservations/index'
  resources :reservations, only: [:index, :destroy]  # 追加

  resources :rooms do
    collection do
      get 'search'
    end
    resources :reservations, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get 'profile'
      put 'profile', to: 'users#update_profile'
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations

  has_one_attached :room_image

  validates :room_name, presence: true
  validates :room_price, presence: true
  validates :room_address, presence: true

  def room_image_url
    if icon.attached?
      icon.variant(resize: "400x300").processed
    else
      default_room_image_url
    end
  end

  def default_room_image_url
    'default-image-room.png'
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[room_name room_address room_intro]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[reservations room_image_attachment room_image_blob user]
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  
  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.new
  end
  
  def create
    @room = current_user.rooms.new(room_params)
    if @room.save
      flash[:notice] = "施設が登録されました"
      redirect_to :rooms
    else
      flash[:alert] = "問題が発生しました。"
      render "new"
    end
  end
  
  def show
    @user = current_user
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def edit
    @user = current_user
    @room = Room.find(params[:id])
  end

  def update
    new_params = room_params
    @room = Room.find(params[:id])
    if @room.update(new_params)
      flash[:notice] = "保存しました。"
      redirect_to rooms_url
    else
      flash[:alert] = "問題が発生しました。"
      render "edit"
    end
  end

  def search
    @q = Room.ransack(params[:q])
    @results = @q.result(distinct: true)
  end

  def destroy
    @room = Room.find(params[:id])
    if @room.destroy
      redirect_to rooms_path, notice: "施設を削除しました"
    else
      flash[:alert] = "問題が発生しました。"
      render "index"
    end
  end
  
  private


  def room_params
    params.require(:room).permit(:room_name, :room_intro, :room_price, :room_address, :room_image)
  end

end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/rooms/edit.html.erb
<%= render "shared/error", obj: @room %>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">

      <h2>施設情報の編集</h2>

      <%= form_with model: @room, local: true do |f| %>
        <div class="mb-3">
          <%= f.label :room_name, "施設名", class: "form-label" %>
          <%= f.text_field :room_name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :room_intro, "施設詳細", class: "form-label" %>
          <%= f.text_area :room_intro, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :room_price, "料金", class: "form-label" %>
          <%= f.text_field :room_price, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :room_address, "住所", class: "form-label" %>
          <%= f.text_field :room_address, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :room_image, "施設画像", class: "form-label" %>
          <%= f.file_field :room_image, class: "form-control" %>
        </div>

        <div class="text-end">
          <%= f.submit "保存", class: "btn btn-primary" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h2>登録済み施設一覧</h2>
    </div>
    <div class="col text-end">
      <%= link_to "施設の新規登録", [:new_room], class: "btn btn-primary mb-3" %>
    </div>
  </div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">画像</th>
        <th scope="col">施設名</th>
        <th scope="col">紹介文</th>
        <th scope="col">料金</th>
        <th scope="col">作成日</th>
        <th scope="col">編集</th>
        <th scope="col">削除</th>
      </tr>
    </thead>
    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td>
            <% if room.room_image.attached? %>
              <%= image_tag url_for(room.room_image.variant(resize: "200x200")), class: "img-fluid" %>
            <% else %>
              <%= image_tag 'default-image-room.png', class: "img-fluid" %>
            <% end %>
          </td>
          <td><%= link_to room.room_name, room %></td>
          <td><%= room.room_intro %></td>
          <td><%= room.room_price %></td>
          <td><%= room.created_at.strftime("%Y-%m-%d") %></td>
          <td><%= link_to "編集", edit_room_path(room), class: "btn btn-primary btn-sm" %></td>
          <td><%= link_to "削除", room_path(room), method: :delete, data: { confirm: "施設を削除しますか？" }, class: "btn btn-danger btn-sm", remote: true %></td>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/new.html.erb
<%= render "shared/error", obj: @room %>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">

      <h3 class="mb-4">施設情報の登録</h3>

      <%= form_with model: @room, local: true do |f| %>
        <div class="mb-3">
          <%= f.label :room_name, "施設名" %>
          <%= f.text_field :room_name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :room_intro, "施設詳細" %>
          <%= f.text_area :room_intro, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :room_price, "料金" %>
          <%= f.text_field :room_price, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :room_address, "住所" %>
          <%= f.text_field :room_address, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= f.label :room_image, "施設画像" %>
          <%= f.file_field :room_image, class: "form-control" %>
        </div>

        <div class="text-center">
          <%= f.submit "保存", class: "btn btn-primary" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/rooms/search.html.erb
<div class="search-container">
  <%= search_form_for @q, url: search_rooms_path, class: "search-field", method: :get do |f| %>
    <%= f.search_field :room_address_cont, placeholder: 'エリア名を入力', class: "w-285" %>
    <%= f.search_field :room_name_or_room_intro_cont, placeholder: 'キーワードを入力', class: "w-285" %>
    <%= f.submit "検索", class: "w-70" %>
  <% end %>
</div>
<div class="container">
  <h2>検索結果</h2>

  <% if @results.present? %>
    <h4>検索結果：<%= @results.count %>件</h4>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
      <% @results.each do |room| %>
        <div class="col">
          <div class="card h-100">
            <% if room.room_image.attached? %>
              <%= image_tag room.room_image.variant(resize: "400x300"), class: "card-img-top" %>
            <% else %>
              <%= image_tag 'default-image-room.png', class: "card-img-top", size: "400x300" %>
            <% end %>
            <div class="card-body">
              <h3 class="card-title"><%= room.room_name %></h3>
              <p class="card-text"><%= room.room_address %></p>
              <p class="card-text"><%= room.room_intro.truncate(30) %></p>
              <p class="card-text"><%= number_to_currency(room.room_price, unit: "¥", format: "%u%n") %></p>
              <%= link_to "詳細はこちら", room_path(room), class: "btn btn-warning" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <h4>検索結果0件</h4>
  <% end %>

</div>

app/views/rooms/show.html.erb
<%= render "shared/error", obj: @room %>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">

      <h2>施設情報の確認</h2>

      <table class="table table-bordered">
        <tbody>
          <tr>
            <th scope="row">施設名</th>
            <td><%= @room.room_name %></td>
          </tr>
          <tr>
            <th scope="row">施設紹介</th>
            <td><%= @room.room_intro %></td>
          </tr>
          <tr>
            <th scope="row">料金</th>
            <td><%= @room.room_price %></td>
          </tr>
          <tr>
            <th scope="row">住所</th>
            <td><%= @room.room_address %></td>
          </tr>
          <tr>
            <th scope="row">施設画像</th>
            <td>
              <% if @room.room_image.attached? %>
                <%= image_tag @room.room_image.variant(resize: "400x300").processed, class: "img-fluid" %>
              <% else %>
                <%= image_tag 'default-image-room.png', size: "400x300", class: "img-fluid" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>

      <!-- 編集画面へ -->
      <% if current_user == @room.user %>
        <%= link_to "編集", edit_room_path(@room), class: "btn btn-primary" %>
      <!-- 予約フォームへ -->
      <% else %>    
        <%= link_to "予約する", new_room_reservation_path(room_id: @room.id, user_id: current_user), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>